<a href="https://colab.research.google.com/github/AidaSadeghi/Deep-Learning-with-pytorch/blob/main/PytorchDummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset

# ==========================================
# 1. Tensor Operations & Fundamentals
# ==========================================
def demonstrate_fundamentals():
    print("--- Section 1: Tensor Fundamentals ---")
    # Creating tensors from lists and NumPy
    list_data = [1, 2, 3, 4]
    tensor_a = torch.tensor(list_data)

    # Random initialization and shape attributes
    random_tensor = torch.rand(3, 3)
    print(f"Random Tensor:\n{random_tensor}")
    print(f"Tensor Shape: {random_tensor.shape}\n")

    # Matrix Multiplication vs Element-wise
    ones = torch.ones(3, 3)
    identity = torch.eye(3)

    matmul_result = torch.matmul(ones, identity)
    element_result = ones * identity

    print(f"Matrix Multiplication Result:\n{matmul_result}")
    print(f"Element-wise Multiplication Result:\n{element_result}\n")

# ==========================================
# 2. Data Preparation (Sample Dataset)
# ==========================================
def prepare_data():
    # Creating a synthetic dataset for binary classification
    X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

    # Split into Train and Test
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Convert to PyTorch Tensors
    X_train = torch.FloatTensor(X_train)
    y_train = torch.FloatTensor(y_train).view(-1, 1)
    X_test = torch.FloatTensor(X_test)
    y_test = torch.FloatTensor(y_test).view(-1, 1)

    train_dataset = TensorDataset(X_train, y_train)
    return DataLoader(train_dataset, batch_size=32, shuffle=True), X_test, y_test

# ==========================================
# 3. Model Architecture (Linear Layers)
# ==========================================
class SimpleNet(nn.Module):
    def __init__(self, input_dim):
        super(SimpleNet, self).__init__()
        # Defining a linear layer structure
        self.layer1 = nn.Linear(input_dim, 16)
        self.relu = nn.ReLU()
        self.output = nn.Linear(16, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.layer1(x))
        x = self.sigmoid(self.output(x))
        return x

# ==========================================
# 4. Training Loop & Gradients
# ==========================================
def train_model():
    train_loader, X_test, y_test = prepare_data()
    model = SimpleNet(input_dim=10)

    criterion = nn.BCELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

    print("--- Section 2: Training the Neural Network ---")
    for epoch in range(5):
        epoch_loss = 0
        for batch_x, batch_y in train_loader:
            # Forward pass
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)

            # Backward pass and gradient calculation
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

        print(f"Epoch {epoch+1} - Average Loss: {epoch_loss/len(train_loader):.4f}")

    # Evaluation
    with torch.no_grad():
        test_outputs = model(X_test)
        predicted = (test_outputs > 0.5).float()
        accuracy = (predicted == y_test).sum() / len(y_test)
        print(f"\nFinal Test Accuracy: {accuracy.item()*100:.2f}%")

if __name__ == "__main__":
    demonstrate_fundamentals()
    train_model()

--- Section 1: Tensor Fundamentals ---
Random Tensor:
tensor([[0.4579, 0.7514, 0.2374],
        [0.6376, 0.5554, 0.2011],
        [0.2707, 0.1367, 0.6216]])
Tensor Shape: torch.Size([3, 3])

Matrix Multiplication Result:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Element-wise Multiplication Result:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

--- Section 2: Training the Neural Network ---
Epoch 1 - Average Loss: 0.5467
Epoch 2 - Average Loss: 0.3470
Epoch 3 - Average Loss: 0.3131
Epoch 4 - Average Loss: 0.3036
Epoch 5 - Average Loss: 0.2975

Final Test Accuracy: 81.50%
